config/routes.rb
Rails.application.routes.draw do

  resources :post_comments
  resources :comments

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :index
  resources :users
  resources :posts
  resources :categories
  
  match 'about', to: 'pages#about', via: [:get]
  match 'contact', to: 'pages#contact', via: [:get]
  match 'reservoir', to: 'pages#reservoir', via: [:get]

  root 'home#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  has_paper_trail


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :posts
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_paper_trail
    has_many :posts
    
    def to_s
    "#{cname}"
    end

end

app/models/post.rb
class Post < ActiveRecord::Base
    has_paper_trail
    belongs_to :category
    belongs_to :user
    has_many :post_comments, :dependent => :destroy
    validates :title, presence: true
    validates :body, length: { minimum: 10 }
    
    def to_s
    "#{title}"
    end
    
end

app/models/post_comment.rb
class PostComment < ActiveRecord::Base
  belongs_to :post
  
  validates_presence_of :name
  validates_length_of :name, :within => 2..20
  validates_presence_of :body
  validates_length_of :body, minimum: 10
end

app/models/user.rb
class User < ActiveRecord::Base
    has_paper_trail
    devise :database_authenticatable, 
          :recoverable, :rememberable, :trackable, :validatable
    before_save { self.email = email.downcase }
    validates :name,    presence: true, length: {minimum: 4, maximum:  50 }
    validates :username,    presence: true, length: {minimum: 4, maximum:  50 }
    VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates :email,   presence: true, length: { maximum: 255 },
                        format: { with: VALID_EMAIL_REGEX },
                        uniqueness: { case_sensitive: false }
    # has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
    
    has_many :posts

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :set_paper_trail_whodunnit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :all_categories
  helper_method :all_posts
  before_filter :site_search
  
  
  def all_categories
    @categories = Category.all
  end
  
  def all_posts
    @posts = Post.all
  end
  
  def site_search
    @q = Post.ransack(params[:q])
    @search_posts = @q.result(distinct: true)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
        @categories = Category.all
  end

  def new
  end

  def create
    @category = Category.new(category_params)
  end

  def update
  end

  def show
    @category = Category.find(params[:id])
    @title = @category.cname
    @posts = @category.posts
  end
  
  private
  
  # Use callbacks to share common setup or constraints between actions.
  def set_categor
    @category = Category.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    params.require(:category).permit(:category_id, :cname)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all.page(params[:page]).per(10)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def reservoir
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < InheritedResources::Base
  
  def create
    @post_comment = PostComment.new(post_comment_params)
    if @post_comment.save
      ;flash[:notice] = "Comment was successfully created."
      redirect_to(@post_comment.post)
    else
      flash[:notice] = "Error creating post_comment: #{@post_comment.errors.full_messages}"
      redirect_to(@post_comment.post)
    end
    
  end

  private

    def post_comment_params
      params.require(:post_comment).permit(:name, :email, :body, :post_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

helper_method :sort_column, :sort_direction

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result.page(params[:page]).per(10)
  end

  def show
    @post = Post.find(params[:id])
    @user = User.all
    @post_comment = PostComment.new(:post => @post)
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
  end

  def update
  end

  def destroy
    @post.destroy
  end
  
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:title, :body, :category_id, :user_id, :admin_user_id, :email)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
  end

  def update
  end

  def destroy
    @user.destroy
  end
  
  private
  
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :email, :username, :password, 
                                 :password_confirmation)
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def sort_link(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    icon = sort_direction == "asc" ? "glyphicon glyphicon-chevron-up" : "glyphicon glyphicon-chevron-down"
    icon = column == sort_column ? icon : ""
    link_to "#{title} <span class='#{icon}'></span>".html_safe, {column: column, direction: direction}
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
<div class="post">
    <h1>Listing Categories</h1>
    <ul>
        <% if @categories.each do |category| %>
              <li><%= link_to category.cname, category %></li>
        <% end.empty? %>
             <p></p>
        <% end %>
    </ul>
</div>

app/views/categories/show.html.erb
<% if @posts.each do |post| %>
<div class="post">
    <h2 class="title"><%= link_to post.title, post %></h2>
    <div class="entry"><%= truncate post.body, length: 260 %></div>
    <div class="byline">
        <div class="meta"> posted by <%= link_to post.user.username, user_path(:id => post.user.id) %> </div>
        <p class="bylinelinks"><%= link_to 'Read more...', post_path(post) %></p>  
    </div>
</div>
<% end.empty?  %>
<div class="post">
    <p style="color:#ffffff;">Sorry, there are no posts in this category.</p>
</div>
<% end  %>

app/views/home/index.html.erb
<% @posts.each do |post| %>
<div class="post">
  <h2 class="title"><%= link_to post.title, post %></h2>
  <div class="entry"><%= truncate post.body, length: 250 %></div>
  <div class="byline">
		<p class="meta">Last edit on <%= post.updated_at.strftime("%b %d, %Y") %>, posted by <%= link_to post.user.username, post.user %></p>
		<p class="bylinelinks"><a href="post.html"><%= link_to 'Read more...', post_path(post) %></p>
	</div>
</div>
<% end %>
<div class="post">
  <div><%= paginate @posts %></div><br><br>
  <div><%= page_entries_info @posts %></div>
</div>    

app/views/layouts/application.html.erb
<%= render "partials/header" %>
	<div id="page">
		<div id="page-bgtop">
			<div id="page-bgbtm">
				<div id="content">
				    <div class="flash-message">
				    <% flash.each do |key, value| %>
                        <p><%= value %></p>
                    <% end %>
				    </div>

				    <%= yield %><!-- This is the main view -->
				    
					<div style="clear: both;">&nbsp;</div>
				</div>
				<!-- end #content -->
<%= render "partials/sidebar" %>				
				<div style="clear: both;">&nbsp;</div>
			</div>
		</div>
	</div>
	<!-- end #page -->
	<div id="footer">
		<p>&copy; 2013, My Ruby Blog - Sample Project</p>
	</div>
</div>
<!-- end #footer -->
</body>
</html>

app/views/pages/about.html.erb
<div class="post">
    <h1>About My Ruby Blog</h1>
    <p>Find me in app/views/pages/about.html.erb</p>
    <h3><b>
       The standard Lorem Ipsum passage, used since the 1500s 
    </b></h3>
    <p>
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
    </p>
    <br />
    <h4>
       Section 1.10.32 of "de Finibus Bonorum et Malorum", written by Cicero in 45 BC 
    </h4>
    <p>
        "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?"
    </p>
    <br />
    <h4>
       1914 translation by H. Rackham 
    </h4>
    <p>
        "But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure?"
    </p>
    <br />
</div>

app/views/pages/contact.html.erb
<div class="post">
    <h1>Pages#contact</h1>
    <p>Find me in app/views/pages/contact.html.erb</p>
</div>

app/views/pages/reservoir.html.erb
<div class="post">
    <h1>Pages#reservoirs</h1>
    <p>Find me in app/views/pages/reservoirs.html.erb</p>
</div>

app/views/partials/_header.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RubyBlog</title>
  <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Abel', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="wrapper">
	<div id="header-wrapper">
		<div id="header">
			<div id="logo">
				<h1><a href="#">My Ruby Blog</a></h1>
				<p>Learning Ruby on Rails</p>
			</div>
			<div id="menu">
            <ul class="main-nav">
                <li><%= link_to "Home", root_path %></li>
                <li><%= link_to "About", about_path %></li>
                <li><%= link_to "Blog", posts_path %></li>
                <li><%= link_to "Contact", contact_path %></li>
                <li><%= link_to "Reservoir", reservoir_path %></li>
            </ul>
            </div>
		</div>
	</div>
<!-- end #header -->

app/views/partials/_post_comment.html.erb
<div class="post_comment">
    <i><%= h post_comment.name %> says:</i><br>
    <%= simple_format h(post_comment.body) %>
</div>

app/views/partials/_sidebar.html.erb
<div id="sidebar">
					<div>
						<ul>
							<li>
								<div id="search" >
									<%= search_form_for @q do |f| %>
									  <%= f.search_field :title_or_body_cont %>
									
									  <%= f.submit %>
									<% end %>
								</div>
								<div style="clear: both;">&nbsp;</div>
							</li>
							<li>
								<h2>Get The Framework</h2>
								<p>You can download Ruby and/or Ruby on Rails for free right now
		                            <br />
		                            <a style="color:#D93544;" href="http://rubyonrails.org/download" target="blank">GET IT NOW</a>
	        					</p>
							</li>
							<li>
								<h2>Categories</h2>
								
								<ul>
							        <% if all_categories.each do |category| %>
							              <li><%= link_to category.cname, category %> &nbsp;&nbsp; (<%= category.posts.count %>)</li>
							        <% end.empty? %>
							            
							        <% end %>
							    </ul>
							</li>
							<li>
								<h2>Blogroll</h2>
								<ul>
							        <% if all_posts.last(10).each do |post| %>
							              <li><%= link_to post.title, post %></li>
							        <% end.empty? %>
							            
							        <% end %>
							    </ul>
							</li>
						</ul>
					</div>
				</div>
				<!-- end #sidebar -->

app/views/posts/index.html.erb
  <% @posts.each do |post| %>
    <div class="post">
      <h2 class="title"><%= link_to post.title, post_path(post) %></h2>
      <div class="entry"><%= post.body %></div>
        <div class="byline">
        	<p class="meta">Last edit on <%= post.updated_at.strftime("%b %d, %Y") %>, posted by <%= link_to post.user.username, post.user %></p>
        	<p class="bylinelinks"><a href="post.html"><%= link_to 'Read more...', post_path(post) %></p>
        </div>
    </div>    
    <% end %>
    <div class="post">
      <div><%= paginate @posts %></div><br><br>
      <div><%= page_entries_info @posts %></div>
    </div>    

app/views/posts/show.html.erb
<div class="post">
  <p>
    <h1>
    <strong><%= @post.title %></strong>
    </h1>
  </p>
  
  <p>
    <%= @post.body %>
  </p>
  
  
  <br>
    <div class="byline">
      <div class="meta">Category: <%= link_to @post.category.cname, category_path(:id => @post.category.id) %></div><br>
    	<div class="meta">Last edit on <%= @post.updated_at.strftime("%b %d, %Y") %>&nbsp-&nbsp  </div>
      <div class="meta"> posted by <%= link_to @post.user.username, user_path(:id => @post.user.id) %> </div>
      <div class="bylinelinks"><%= link_to 'Back', :back %></div><div class="bylinelinks"></div>
  	</div>
  	<br>
  	<hr>
    
    <h4><strong>Add a comment:</strong></h4>
    <br>
    <%= form_for @post_comment do |f| %>
      
      <%= f.hidden_field :post_id %>
      
      <p>
        <%= f.label :name %><br />
        <%= f.text_field :name %>
      </p>
      
      <p>
        <%= f.label :email %><br />
        <%= f.text_field :email %>
      </p>
    
      <p>
        <%= f.label :body %><br />
        <%= f.text_area :body %>
      </p>
    
      <p>
        <%= f.submit "Post Comment" %>
      </p>
      
    <% end %>
    <hr>
        <h4><strong>Comments by other users:</strong></h4>
    <br>
    <%= render :partial => "partials/post_comment", :collection => @post.post_comments %>
</div>


<br><br><br><br>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', :back %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Username</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.username %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/users/show.html.erb
<div class="post">
  <p id="notice"><%= notice %></p>
  <p>
    <h2><%= @user.name %></h2>
  </p>
  
  <h3>Blog Posts</h3>
								
	<ul>
      <% if @user.posts.each do |post| %>
            <li><%= link_to post.title, post %></li>
      <% end.empty? %>
          
      <% end %>
  </ul>
  
  <%= link_to 'Back', :back %>
</div>
<br>